- name: Arch Linux Installation script, Arch + Sway
  connection: local
  hosts: localhost
  tasks:

    - name: Setup pacman
      become: True
      copy:
        src: dots/sys/pacman.conf
        dest: /etc/pacman.conf

    - name: Install packages
      become: True
      pacman:
        name:
          # aestethic
          - lolcat
          - figlet
          - neofetch
          # wm sway
          - sway
          - swaylock
          - swayidle
          - swaybg
          - waybar
          - wl-clipboard
          - wofi
          - grim
          - slurp
          # system configuration
          - light
          - pavucontrol
          - libinput
          - bumblebee
          # utilities
          - htop
          - tmux
          - bat
          - stow
          - nmap
          - ripgrep
          - wireshark-cli
          - wireshark-qt
          - lxappearance
          - polkit
          - lxsession
          # development
          - git
          - jdk17-openjdk
          - base-devel
          - texlive-most
          - texstudio
          - neovim
          - python-pynvim
          - rustup
          # virtualization
          - docker
          - virt-manager
          - qemu-desktop
          - libvirt
          - edk2-ovmf
          - dnsmasq
          # binary exp tools
          - ghidra
          - radare2
          - r2ghidra
          - pwndbg
          - debuginfod
          # vpn
          - tailscale
          - openvpn
          # desktop apps
          - telegram-desktop
          - libreoffice
          - firefox
          - chromium
          - zathura
          - zathura-pdf-mupdf
          - thunderbird
          - fuse
          - pcmanfm
          # terminal
          - alacritty
          - zsh
          - lsd
          # fonts
          - ttf-fira-code
          - ttf-font-awesome
        state: present

    - name: Enable services
      shell:
        cmd: sudo systemctl enable bumblebeed laptop-mode tailscaled ly libvirtd docker

    - name: Make zathura the default pdfviewer
      shell:
        cmd: xdg-mime default org.pwmt.zathura.desktop application/pdf
          
    - name: Installing pwntools and z3-solver
      pip:
        name:
          - pwntools
          - z3-solver

    - name: Setup libinput
      become: True
      copy:
        src: dots/sys/30-touchpad.conf
        dest: /etc/X11/xorg.conf.d/30-touchpad.conf

    - name: Install packer, neovim's plugin manager
      git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        clone: yes
        update: yes

    - name: Add neovim configuration
      git:
        repo: git@github.com:sioel0/slnvim
        dest: ~/.config/nvim
        depth: 1
        clone: yes
        update: yes

    - name: Set nvim as git editor
      git_config:
        name: core.editor
        scope: global
        value: nvim
    
    - name: Set git user.name
      git_config:
        name: user.name
        scope: global
        value: "{{username}}"

    - name: Set git user.email
      git_config:
        name: user.email
        scope: global
        value: "{{email}}"

    - name: Sign commits by default
      git_config:
        name: commit.gpgsign
        scope: global
        value: true

    - name: Install oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -s -- -y

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes
            

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes

    - name: install powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes
        update: yes

    - name: Download dotfiles
      git:
        repo: git@github.com:sioel0/dotfiles
        dest: ~/Projects/dotfiles
        clone: yes
        update: yes

    - name: Set zsh as default user shell
      become: True
      user:
        name: "{{ansible_user_id}}"
        shell: /usr/bin/zsh
