- name: Arch Linux Installation script, Arch + Hyprland
  connection: local
  hosts: localhost
  tasks:

    - name: Remove archinstall logs
      ansible.builtin.file:
        path: /var/log/archinstall
        state: absent

    - name: Update pacman.conf settings
      become: True
      lineinfile:
        path: /etc/pacman.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#Color', line: 'Color' }
        - { regexp: '^#VerbosePkgLists', line: 'VerbosePkgLists' }
        - { regexp: '^#ParallelDownloads', line: 'ParallelDownloads = 10' }

    - name: Install reflector
      become: True
      pacman:
        name: reflector
        state: present

    - name: Update reflector settings
      lineinfile:
        path: /etc/xdg/reflector/reflector.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^# --country France,Germany', line: '--country Italy,Germany, France' }
        - { regexp: '^--latest', line: '--latest 50' }

    - name: Enable Reflector.timer
      systemd:
        name: reflector.timer
        state: started
        enabled: yes
  
    - name: Install packages
      become: True
      pacman:
        name:
          # aestethic
          - lolcat
          - figlet
          - neofetch
          # wm
          - hyprland
          - swaylock
          - swaybg
          - xdg-desktop-portal-hyprland
          - polkit-kde-agent
          - qt5-wayland
          - qt6-wayland
          - mako
          - cliphist
          # system configuration
          - light
          - pavucontrol
          - bumblebee
          # utilities
          - htop
          - tmux
          - bat
          - stow
          - unzip
          - nmap
          - ripgrep
          - xorg-xwayland
          - udisks2
          - slurp
          - grim
          # development
          - git
          - base-devel
          - helix
          - rustup
          # virtualization
          - docker
          - virt-manager
          - qemu-desktop
          - libvirt
          - edk2-ovmf
          - dnsmasq
          # vpn
          - tailscale
          - openvpn
          # desktop apps
          - telegram-desktop
          - libreoffice
          - firefox
          - zathura
          - zathura-pdf-mupdf
          - thunderbird
          - pcmanfm
          # terminal
          - foot
          - zsh
          - lsd
          # fonts
          - ttf-font-awesome
        state: present

    - name: Install rustup toolchain
      shell:
        cmd: rustup toolchain install stable

    - name: Create aur_builder user for paru installation
      user:
        name: aur_builder
        create_home: False
 
    - name: Give aur_builder user pacman privileges
      lineinfile:
        path: /etc/sudoers.d/11_aur_builder
        state: present
        line: "aur_builder ALL+(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        mode: 0644
        validate: /usr/sbin/visudo -cf %s

    - name: Install paru
      become: yes
      become_user: aur_builder
      args:
        creates: /usr/bin/paru
      shell: |
        git clone https://aur.archlinux.org/paru.git /tmp/paru
        cd /tmp/paru
        yes | makepkg -si
        cd -
        rm -rf /tmp/paru

    - name: Install aur packages via paru
      become: yes
      become_user: aur_builder
      pacman:
        name:
          - ly
          - spotify
          - wob
          - tofi-git
      executable: paru
      state: present

    - name: Enable services
      shell:
        cmd: sudo systemctl enable bumblebeed laptop-mode tailscaled libvirtd docker udisks2 ly

    - name: Make zathura the default pdfviewer
      shell:
        cmd: xdg-mime default org.pwmt.zathura.desktop application/pdf

    - name: Set helix as git editor
      git_config:
        name: core.editor
        scope: global
        value: helix
    
    - name: Set git user.name
      git_config:
        name: user.name
        scope: global
        value: sioel0

    - name: Set git user.email
      git_config:
        name: user.email
        scope: global
        value: leonisimone@pm.me

    - name: Sign commits by default
      git_config:
        name: commit.gpgsign
        scope: global
        value: true

    - name: Setup gpg signing key for commits
      git_config:
        name: commit.signingkey
        scope: global
        value: "{{signing_gpg_key}}"

    - name: Setup global gitignore
      git_config:
        name: core.excludesfile
        scope: global
        value: /home/sioel0/.gitignore_global

    - name: Install oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -s -- -y

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes

    - name: Install powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes
        update: yes

    - name: Set zsh as default user shell
      become: True
      user:
        name: sioel0
        shell: /usr/bin/zsh

    - name: Install dotfiles
      shell:
        cmd: ./install.sh
