- name: Arch Linux Installation script, Arch+i3
  connection: local
  hosts: localhost
  tasks:

    - name: Setup pacman
      become: True
      copy:
        src: dots/sys/pacman.conf
        dest: /etc/pacman.conf

    - name: Install packages
      become: True
      pacman:
        name:
          # aestethic
          - lolcat
          - figlet
          - cowsay
          - neofetch
          # wm
          - i3-gaps
          - i3status
          - i3lock
          - rofi
          - nitrogen
          - xorg
          - xorg-server
          - xorg-xmodmap
          - xorg-xrdb
          - dunst
          - picom
          # system configuration
          - light
          - pavucontrol
          - libinput
          - bumblebee
          # utilities
          - htop
          - tmux
          - bat
          - stow
          - zoxide
          - nmap
          - ripgrep
          - wireshark-cli
          - wireshark-qt
          - fuse
          - lxappearance
          - polkit
          # development
          - git
          - jdk17-openjdk
          - base-devel
          - texlive-most
          - texstudio
          - neovim
          - rustup
          # virtualization
          - docker
          - virt-manager
          - qemu-desktop
          - libvirt
          - edk2-ovmf
          - dnsmasq
          - iptables-nft
          # binary exp tools
          - ghidra
          - radare2
          - r2ghidra
          - pwndbg
          # vpn
          - tailscale
          # desktop apps
          - telegram-desktop
          - libreoffice
          - firefox
          - chromium
          - thunderbird
          - zathura
          - zathura-pdf-mupdf
          # terminal
          - xterm
          - fish
        state: present

    - name: Enable services
      shell:
        cmd: sudo systemctl enable bumblebeed laptop-mode tailscaled ly libvirtd docker
    
    - name: Create basic directories structure
      file:
        path: 
          - ~/Projects
          - ~/tools
          - ~/Downloads
          - ~/Documents
          - ~/Pictures
        state: directory

    - name: Clone ghidra-dark
      git:
        repo: https://github.com/zackelia/ghidra-dark
        dest: ~/tools/ghidra-dark
        clone: yes
        update: yes

    - name: Installing pwntools and z3-solver
      pip:
        name:
          - pwntools
          - z3-solver

    - name: Setup libinput
      become: True
      copy:
        src: dots/sys/30-touchpad.conf
        dest: /etc/X11/xorg.conf.d/30-touchpad.conf

    - name: Install packer, neovim's plugin manager
      git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        clone: yes
        update: yes

    - name: Add neovim configuration
      git:
        repo: git@github.com:sioel0/slnvim
        dest: ~/.config/nvim
        clone: yes
        update: yes

    - name: Set nvim as git editor
      git_config:
        name: core.editor
        scope: global
        value: nvim
    
    - name: Set git user.name
      git_config:
        name: user.name
        scope: global
        value: "{{username}}"

    - name: Set git user.email
      git_config:
        name: user.email
        scope: global
        value: "{{email}}"

    - name: Install tmux plugin manager tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        clone: yes
        update: yes

    - name: Setup dotfiles
      shell:
        cmd: dots/install.sh

    - name: Install fisher, fish plugin manager
      shell:
        cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

