- name: Arch Linux Installation script, Arch + Hyprland
  connection: local
  hosts: localhost
  vars_files:
    - setup.yml
  tasks:

    - name: Rog specific setup
      include_role:
        name: rog
      when: rog|bool

    - name: Package management
      include_role:
        name: packages
      when: packages|bool

    - name: Housekeeping stuff
      include_role:
        name: housekeeping
      when: housekeeping|bool

    - name: Git setup
      include_role:
        name: git
      when: git|bool

    - name: Hardening settings
      include_role:
        name: hardening
      when: hardening|bool

    - name: Nvidia setup
      include_role:
        name: nvidia
      when: nvidia|bool

    - name: Install packages for CTFs
      include_role:
        name: ctf
      when: ctf|bool

