---
# tasks file for nvidia
- name: Install nvidia packages
  become: True
  pacman:
    name: nvidia

- name: nvidia drm kernel modeset
  copy:
    dest: /etc/modeprobe.d/nvidia.conf
    content: options nvidia_drm modeset=1

- name: Create pacman hook
  copy:
    dest: /etc/pacman.d/hooks/nvidia.hook
    content: |
      [Trigger]
      Operation=Install
      Operation=Upgrade
      Operation=Remove
      Type=Package
      Target=nvidia
      Target=linux

      [Action]
      Description=Updating NVIDIA module in initcpio
      Depends=mkinitcpio
      When=PostTransaction
      NeedsTargets
      Exec=/bin/sh -c 'while read -r trg; do case $trg in linux*) exit 0; esac; done; /usr/bin/mkinitcpio -P'
