---
# tasks file for git
- name: Set git editor
  git_config:
    name: core.editor
    scope: global
    value: "{{ git_editor }}"

- name: Set git user.name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"

- name: Set git user.email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
