#!/bin/bash

declare -a options=(
"logout"
"reboot"
"shutdown"
"quit"
)
CHOICE=$(printf '%s\n' "${options[@]}" | wofi -d -p "Choice:")

case $CHOICE in
  'logout')
    swaymsg exit
  ;;
  'reboot')
    sudo reboot
  ;;
  'shutdown')
    sudo poweroff
  ;;
  'quit')
    exit 0
  ;;
  *)
    exit 0
  ;;
esac
