#!/bin/bash

# options for the script
declare -a options=(
"open"
"search"
"bookmark"
)
# chose an option
CHOICE=$(printf '%s\n' ${options[@]} | wofi -d -p "Choice:")
case $CHOICE in
  # open qutebrowser as is
  'open')
    qutebrowser
  ;;
  # search something
  'search')
    qutebrowser "$(wofi -d -p "Search")"
  ;;
  # open a quickmark
  'bookmark')
    open qutebrowser directly in a quickmark
    URL=$(cat ~/.config/qutebrowser/quickmarks | wofi -d -p "Bookmark:" | cut -d ' ' -f2)
    qutebrowser $URL
  ;;
  # any other option give error code
  *)
  exit 1
  
esac
