---
# tasks file for rog
- name: Add g14 repo keys
  become: True
  shell: |
    pacman-key --recv-keys 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
    pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
    pacman-key --lsign-key 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
    pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35

- name: Update pacman.conf
  become: True
  lineinfile:
    path: /etc/pacman.conf
    line: '{{ item.line }}'
    state: present
  loop:
    - { line: '[g14]' }
    - { line: 'Server = https://arch.asus-linux.org'}

- name: Pacman -Syu
  become: True
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  become: True
  pacman:
    name:
      - asusctl
      - power-profiles-daemon
      - supergfxctl
      - switcheroo-control
      - rog-control-center
    state: present

- name: Enable system services
  become: True
  systemd:
    enabled: True
    name: "{{ item }}"
  with_items:
    - power-profiles-daemon
    - supergfxd
    - switcheroo-control
