---
# tasks file for housekeeping
- name: Remove archinstall logs
  become: True
  ansible.builtin.file:
    path: /var/log/archinstall
    state: absent

- name: Enable services
  become: True
  systemd:
    enabled: True
    name: "{{ item }}"
  with_items:
    - ly
    - libvirtd
    - docker
    - udisks2

- name: Make zathura the default pdfviewer
  shell:
    cmd: xdg-mime default org.pwmt.zathura.desktop application/pdf

- name: Set zsh as default user shell
  become: True
  user:
    name: "{{ lookup('env', 'USER')}}"
    shell: /usr/bin/zsh

- name: Install dotfiles
  shell:
    cmd: |
      cd dots
      ./install.sh

- name: Create polkit repo
  file:
    path: /etc/polkit1/rules.d
    state: directory

- name: Polkit rule for poweroff and reboot
  become: True
  copy:
    dest: /etc/polkit1/rules.d/60-poweroff_reboot.rules
    content: |
      polkit.addRule(function(action, subject) {
        if ((action.id == "org.freedesktop.login1.reboot" ||
             action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
             action.id == "org.freedesktop.login1.power-off" ||
             action.id == "org.freedesktop.login1.power-off-multiple-sessions") &&
             subject.isInGroup("wheel")) {
               return polkit.Result.YES;
             }
      });
